### ISSUE TITLE
FDP Client unable to load metadata from FDP

### ISSUE THREAD

**Issue by raar1** [FAIRDataTeam/FAIRDataPoint-Example#1]
Hello,

We are running into some issues using this Example, and hopefully there's a simple fix.

The Client spins up successfully, and it is possible to log in via the browser as either of two users (Nikola Tesla or Albert Einstein) as in the public [documentation](https://fairdatapoint.readthedocs.io/en/latest/). However, the message "Unable to get repository data" is displayed on the entry page, and an "Unable to load dashboard" message is displayed when "My Metadata" is selected.

![Screenshot_2020-02-05FAIRDataPoint](https://user-images.githubusercontent.com/2650951/73850728-8710af80-482c-11ea-84d3-730aac52c8ac.png))

In the docker logs for the FAIRDataPoint we see the following error:
```
2020-02-05 13:38:44,506 132686 [http-nio-80-exec-2] ERROR nl.dtls.fairdatapoint.api.controller.exception.ExceptionControllerAdvice - No metadata found for the uri : http://192.168.99.100
```

There are no obviously (to me) related errors in the logs for the Client or MongoDB services. I include the full logs for all three services below, in case you wish to see in more detail:

[fdp_client_docker_log.txt](https://github.com/FAIRDataTeam/FAIRDataPoint-Example/files/4159977/fdp_client_docker_log.txt)
[fdp_docker_log.txt](https://github.com/FAIRDataTeam/FAIRDataPoint-Example/files/4159978/fdp_docker_log.txt)
[mongo_docker_log.txt](https://github.com/FAIRDataTeam/FAIRDataPoint-Example/files/4159979/mongo_docker_log.txt)

None of the config files etc in this repo were modified before running.

Do you have any idea what might be the issue here? Many thanks for your help.

**Comment by vknaisl** [comment]
Hello Robin,

That's strange. Did you access the FDP on `http://localhost` in the browser?

Regards,
Vojtech

**Comment by raar1** [comment]
Hi Vojtech,

Yes, although in my case localhost is the IP of the VM in which docker is running (this is why 192.168.99.100 appears in the logs and not 127.0.0.1). In this case I was running docker on a Mac, but the same problem appears on an Ubuntu machine.

Browser is firefox 72.02 and docker 19.03.5, although I wouldn't expect small version differences to matter here...

Best,

Robin

**Comment by bakhshir** [comment]
Same here, but on the Ubuntu 18.04 system and firefox 72.01 (also on chromium). Somewhat related, the documentation is not accessible via http://localhost:8080/swagger-ui.html 

-Rena

**Comment by vknaisl** [comment]
Hello Robin and Rena,

I am sorry for your inconvenience. 

@Robin: Your metadata is bound to the concrete URL. The default in the example is the `localhost`. If you want to have it on `192.168.99.100`, you have to configure the `instance.url` property in the server configuration [1]. 

@Rena: You have a problem just with Swagger documentation or also with running the FDP as itself?

Regards,
Vojtech

[1] https://github.com/FAIRDataTeam/FAIRDataPoint/blob/develop/src/main/resources/application-production.yml

**Comment by bakhshir** [comment]
Hi Vojtech, I have problem with both. In the docker logs, I see this relevant line (to my problem with FDP):

> client_1  | 2020/02/05 21:13:47 [error] 19#19: *75 open() "/usr/share/nginx/html/my-metadata" failed (2: No such file or directory), client: 172.24.0.1, server: localhost, request: "GET /my-metadata HTTP/1.1", host: "localhost"

I wonder how one sets the folder right. I used the yaml file, that you are referring to.

**Comment by vknaisl** [comment]
Hello Rena,

Did you mount it inside Docker container? If not, here is an example of `docker-compose.yml` and instructions on how to mount it [1].

Regards,
Vojtech

[1] https://fairdatapoint.readthedocs.io/en/latest/deployment/configuration.html

**Comment by bakhshir** [comment]
Hi Vojtech, Yes, this is the line from docker logs, so unfortunately, your suggestion does not apply.

**Comment by bakhshir** [comment]
Just to be clear, for the installation of FDP, I'm using the FDP docker image. I tried variation on the yaml file, but I see the same screen as Robin reported. I can change users but cannot view dashboard or see  metadata catalog. 

> $ docker-compose logs | grep "error"
> client_1  | 2020/02/07 15:47:42 [error] 18#18: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.2:80/", host: "localhost", referrer: "http://localhost/"
> client_1  | 2020/02/07 15:47:56 [error] 18#18: *3 open() "/usr/share/nginx/html/fdp/catalog" failed (2: No such file or directory), client: 172.26.0.1, server: localhost, request: "GET /fdp/catalog HTTP/1.1", host: "localhost"
> client_1  | 2020/02/07 15:48:00 [error] 18#18: *1 "/usr/share/nginx/html/fdp/index.html" is not found (2: No such file or directory), client: 172.26.0.1, server: localhost, request: "GET /fdp/ HTTP/1.1", host: "localhost"
> client_1  | 2020/02/07 16:00:32 [error] 18#18: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.2:80/", host: "localhost", referrer: "http://localhost/"
> client_1  | 2020/02/07 16:00:38 [error] 18#18: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "http://172.26.0.2:80/dashboard", host: "localhost", referrer: "http://localhost/my-metadata"
 

This is what i see in my docker logs. Would you suggest to report the issue in the FDP main repo?

**Comment by janslifka** [comment]
Hello Rena, did you try this example as it is or did you change the configuration somehow? Could you share how exactly your docker-compose file and application config look like?

**Comment by bakhshir** [comment]
Hi, 

Just to be clear, I tried application-production.yml from this repo, I tried the one from the docs above, and I tried to modify it. Nothing worked. I would appreciate the assistance. 

Here are my docker-compose and current config files:
[docker-compose.yml](https://github.com/FAIRDataTeam/FAIRDataPoint-Example/files/4180413/docker-compose.yml.txt)
[application-production.yml](https://github.com/FAIRDataTeam/FAIRDataPoint-Example/files/4180416/application-production.yml.txt)

Do this help?

-Rena

**Comment by janslifka** [comment]
Are you sure this is the application-production.yml file that you use? Because the content is a docker-compose file.

Anyway, if you pull this repository and without any changes run `docker-compose up -d` what are the errors in the log? You can use `docker-compose logs -f` to follow the log. You should eventually see a message like this: 

```
server_1  | 2020-02-10 12:52:38,666 18574 [main] INFO  nl.dtls.fairdatapoint.Application - Started Application in 16.293 seconds (JVM running for 18.707)
```

**Comment by bakhshir** [comment]
This is my application-production.yml: https://github.com/FAIRDataTeam/FAIRDataPoint/blob/develop/src/main/resources/application-production.yml 

I did not make any changes initially. Now I tried again with no success.  I do see the message similar to yours:  

`server_1  | 2020-02-10 17:44:46,345 16730 [main] INFO  nl.dtls.fairdatapoint.Application - Started Application in 15.107 seconds (JVM running for 16.845)
`

But I neither get the "repository data" nor "the dashboard".

**Comment by kburger** [comment]
I've been able to get the error once, but cannot seem to reproduce it again (all using the stock `docker-compose.yml` and `application-production.yml` files). For completeness sake, my setup:

```
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76
```

```
$ docker-compose --version
docker-compose version 1.25.4, build 8d51620a
$ docker --version
Docker version 19.03.5, build 633a0ea
```

```
$ docker-compose images
          Container                       Repository              Tag       Image Id       Size  
-------------------------------------------------------------------------------------------------
fairdatapoint-example_client_1   fairdata/fairdatapoint-client   1.0.0    48b1b1f05e74   51.08 MB
fairdatapoint-example_mongo_1    mongo                           4.0.12   f9653b81b56d   414.5 MB
fairdatapoint-example_server_1   fairdata/fairdatapoint          1.0.0    953e91f109f6   471 MB
```

Cleaning the cwd (`mongo` and `rdfdata` folders) and docker images might help. Depending on your setup you might want to pick which images to remove, or do a clean sweep using `docker rmi $(docker images -a -q)` which wil remove _all_ images on your local machine. Cleaning the browser cache could help too, in my initial erroneous state firefox kept displaying the error while chrome (after cleaning the cache) worked.

If these issues still remain, we could make an appointment to figure everything out in person.

**Comment by bakhshir** [comment]
I tried all of the above. Cleaned up everything, and installed from the scratch. Again, running Ubuntu 18.04 with 
fairdata/fairdatapoint:1.0.0
fairdata/fairdatapoint-client:1.0.0
mongo:4.0.12

docker images. I tried both Firefox 72.0.1 and Chrome v 79.0.3945.79. Now I don't even get users dashboard. 

We suspect the problem is with the client. And you guys probably have the database/datastore already populated when you install FDP server and client.

**Comment by janslifka** [comment]
Hello, we've released a new version of the FAIR Data Point (1.1.0) with a simplified configuration and updated the documentation, including a new section about local deployment [1]. You can try to follow the steps there if it helps.

[1] https://fairdatapoint.readthedocs.io/en/latest/deployment/local-deployment.html

**Comment by bakhshir** [comment]
Thanks for the info. I tried the new docker compose yaml from readtehdocs.io pages, but i now get this error:

> In file './docker-compose.yml', service must be a mapping, not a NoneType.

Something is missing from the current example config file.

**Comment by janslifka** [comment]
Thanks, there was an issue with the indentation in the docs. I fixed and tested that. When I run `docker-compose up -d` with the updated version now, I can open the FAIR Data point on http://localhost once it started.

**Comment by bakhshir** [comment]
Ok, it finally works. The client says that there is no metadata but there are no errors anymore. Thanks for the help here.

**Comment by bakhshir** [comment]
On the side note: the swagger doc still does not work, but now i see 404 page. So, probably because it is not configured properly.
